### ISSUE TITLE
ReferenceError: appInsights is not defined

### ISSUE THREAD

**Issue by nssidhu** [IvanJosipovic/BlazorApplicationInsights#105]
I am getting the following Error

I am using .NET 6 RC1 Web Assembly Hosted Project

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: appInsights is not defined
      ReferenceError: appInsights is not defined
          at Object.addTelemetryInitializer (https://localhost:5001/_content/BlazorApplicationInsights/JsInterop.js:32:9)
          at https://localhost:5001/_framework/blazor.webassembly.js:1:3297
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3271)
          at Object.At [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:58349)
          at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:193753)
          at wasm://wasm/00945eda:wasm-function[2590]:0x8073e
          at wasm://wasm/00945eda:wasm-function[2310]:0x68ada
          at wasm://wasm/00945eda:wasm-function[7015]:0x17bca9
          at wasm://wasm/00945eda:wasm-function[6830]:0x172e4f
Microsoft.JSInterop.JSException: appInsights is not defined
ReferenceError: appInsights is not defined
    at Object.addTelemetryInitializer (https://localhost:5001/_content/BlazorApplicationInsights/JsInterop.js:32:9)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:3297
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3271)
    at Object.At [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:58349)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:193753)
    at wasm://wasm/00945eda:wasm-function[2590]:0x8073e
    at wasm://wasm/00945eda:wasm-function[2310]:0x68ada
    at wasm://wasm/00945eda:wasm-function[7015]:0x17bca9
    at wasm://wasm/00945eda:wasm-function[6830]:0x172e4f
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorApplicationInsights.ApplicationInsights.AddTelemetryInitializer(TelemetryItem telemetryItem)
   at Program.<>c.<<<Main>$>b__0_2>d.MoveNext() in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Client\Program.cs:line 63
--- End of stack trace from previous location ---
   at BlazorApplicationInsights.ApplicationInsights.InitBlazorApplicationInsightsAsync(IJSRuntime jSRuntime)
   at BlazorApplicationInsights.ApplicationInsightsComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
Here is my app.razor

```
<ApplicationInsightsComponent />
<CascadingAuthenticationState>
       <CascadingBlazoredModal>
<Error>
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p role="alert">Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</Error>
 </CascadingBlazoredModal>
</CascadingAuthenticationState>
```

Here is the program.cs

```
using XXXXXXXV6New.Client;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Blazored.LocalStorage;
using XXXXXXV6New.Client.Services;
using Blazored.Modal;
using Serilog;
using Syncfusion.Blazor;
using Microsoft.AspNetCore.Components.Authorization;
using Serilog.Core;
using Serilog.Events;
using System.Diagnostics;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Components;
using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Http.Connections;
using System.Net.Http;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.Extensions.Configuration;
using System.Configuration;
using Serilog.Sinks;
using Toolbelt.Blazor.Extensions.DependencyInjection;
using BlazorApplicationInsights;
using System.Collections.Generic;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");

builder.Services.AddBlazoredLocalStorage();


builder.Services.AddScoped<AppState>();
builder.Services.AddScoped<PageTransferDisplayMessage>();
builder.Services.AddScoped<OrgService>();
builder.Services.AddScoped<CustomHttpService>();

builder.Services.AddSpeechSynthesis(); // <- Add this line.

builder.Services.AddBlazoredModal();
builder.Services.AddSyncfusionBlazor();
builder.Services.AddLogging(configure => configure.AddSerilog());

builder.Services.AddTransient<CustomHttpMessageHandler>();

builder.Services.AddHttpClient("default", client =>
{
    client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
})
.AddHttpMessageHandler<CustomHttpMessageHandler>();

//https://awesomeopensource.com/project/IvanJosipovic/BlazorApplicationInsights
builder.Services.AddBlazorApplicationInsights(async applicationInsights =>
{
    var telemetryItem = new TelemetryItem()
    {
        Tags = new Dictionary<string, object>()
            {
                { "ai.cloud.role", "XXXXXXXNewV6" },
                { "ai.cloud.roleInstance", "XXXXXXXNewV6" },
            }
    };

    await applicationInsights.AddTelemetryInitializer(telemetryItem);
});

builder.Services.AddAuthorizationCore();

builder.Services.AddScoped<CustomAuthenticationStateProvider>();
builder.Services.AddScoped<AuthenticationStateProvider>(provider => provider.GetRequiredService<CustomAuthenticationStateProvider>());

Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense('')

var levelSwitch = new LoggingLevelSwitch();
levelSwitch.MinimumLevel = LogEventLevel.Information;

//TelemetryConfiguration.Active.InstrumentationKey = builder.Configuration["ApplicationInsights:InstrumentationKey"];

var loggingConfig = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Enrich.WithProperty("Source", "BlazorWebAssembly")
    .Enrich.WithProperty("AppName", "XXXXXXXV6")
    .Enrich.WithProperty("InstanceId", Guid.NewGuid().ToString("n"))
    // .MinimumLevel.
    // .WriteTo.BrowserHttp(controlLevelSwitch: levelSwitch)
    //.WriteTo.Console() Not supported on Blazor Wasm as there is no console, it runs in the browser.
    .WriteTo.BrowserConsole();
    //.WriteTo.BrowserHttp($"{builder.HostEnvironment.BaseAddress}ingest", controlLevelSwitch: levelSwitch);
   // .WriteTo.ApplicationInsightsTraces(TelemetryConfiguration.Active);
//.WriteTo.BrowserHttp(endpointUrl: Environment.GetEnvironmentVariable("SEQ_URL") ?? "http://localhost:5341"),   //http://5.9.10.113/67073040/send-serilog-requests-to-http-endpoint
// .CreateLogger();

Log.Logger = loggingConfig.CreateLogger();

builder.Services.AddSingleton<LoggingLevelSwitch>(levelSwitch);

Serilog.Debugging.SelfLog.Enable(msg =>
{
    Console.WriteLine("Error in Serilog " + msg);
    //Debugger.Break();
});

builder.Services.AddSingleton<HubConnection>(sp => {
    var navigationManager = sp.GetRequiredService<NavigationManager>();
    return new HubConnectionBuilder()
      .WithUrl(navigationManager.ToAbsoluteUri("/XXXXXXXneHub"))
      .WithAutomaticReconnect()
      .Build();
});

await builder.Build().RunAsync();

```

**Comment by nssidhu** [comment]
yes, like this in Index.html

 <script src="_content/BlazorApplicationInsights/JsInterop.js"></script>

    <script type="text/javascript">
        !function (T, l, y) { // Removed for brevity...
            src: "https://js.monitor.azure.com/scripts/b/ai.2.min.js",
                ld: -1,  // Set this to -1
                    crossOrigin: "anonymous",
                        cfg: {
                instrumentationKey: "XXXXXXXX"
            }
        });
    </script>
