### ISSUE TITLE
Unable to add ApplicationInsightsComponent to App.razor

### ISSUE THREAD

**Issue by yelanjri** [IvanJosipovic/BlazorApplicationInsights#214]
Hi I just did everything like in the Readme but I am stuck with adding the component to the app.razor file.
I am getting this error in the browser console:
```
Error: Microsoft.JSInterop.JSException: Could not find 'appInsights.trackPageView' ('appInsights' was undefined).
Error: Could not find 'appInsights.trackPageView' ('appInsights' was undefined).
    at https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at s.findFunction (https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:465)
    at E (https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:2611)
    at https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:3499
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://localhost:44378/dev-mijn/_framework/blazor.server.js:1:67009)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorApplicationInsights.ApplicationInsights.TrackPageView(String name, String uri, String refUri, String pageType, Nullable`1 isLoggedIn, Dictionary`2 properties)
   at BlazorApplicationInsights.ApplicationInsightsComponent.NavigationManager_LocationChanged(Object sender, LocationChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```
I have added the service like this to my startup :
`services.AddBlazorApplicationInsights();`
And added it to the top of my App.razor file.

Anyone any idea how I can fix this? I have no clue. I will try debugging this meanwhile

**Comment by IvanJosipovic** [comment]
Hey,

You are missing the app insights javascript. See the sample, https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/298c81c3f999f4c54fe6565e92062147210c4a6e/src/BlazorApplicationInsights.Sample/wwwroot/index.html#L9

**Comment by IvanJosipovic** [comment]
You modified the JavaScript, please revert name back to appInsights.

"name: "Test name", // Global SDK Instance name defaults to "appInsights" when not supplied"
