### ISSUE TITLE
Unhandled exception rendering component: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by HMoen** [IvanJosipovic/BlazorApplicationInsights#46]
First of, thanks for this awesome project.

Just now we started getting the following error in the browser. I assume it's an azure issue since your site https://blazorapplicationinsights.netlify.app/ is experiencing same error upon load.

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'push' of undefined
      TypeError: Cannot read property 'push' of undefined
          at Object.m.<computed> [as addTelemetryInitializer] (https://blazorapplicationinsights.netlify.app/:10:3524)
          at Object.addTelemetryInitializer (https://blazorapplicationinsights.netlify.app/_content/BlazorApplicationInsights/JsInterop.js:32:21)
          at https://blazorapplicationinsights.netlify.app/_framework/blazor.webassembly.js:1:9805
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://blazorapplicationinsights.netlify.app/_framework/blazor.webassembly.js:1:9773)
          at _mono_wasm_invoke_js_marshalled (https://blazorapplicationinsights.netlify.app/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
          at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
          at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
Microsoft.JSInterop.JSException: Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
    at Object.m.<computed> [as addTelemetryInitializer] (https://blazorapplicationinsights.netlify.app/:10:3524)
    at Object.addTelemetryInitializer (https://blazorapplicationinsights.netlify.app/_content/BlazorApplicationInsights/JsInterop.js:32:21)
    at https://blazorapplicationinsights.netlify.app/_framework/blazor.webassembly.js:1:9805
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://blazorapplicationinsights.netlify.app/_framework/blazor.webassembly.js:1:9773)
    at _mono_wasm_invoke_js_marshalled (https://blazorapplicationinsights.netlify.app/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
    at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2044730 + 0x0002c> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x1fbf840 + 0x000e4> in <filename unknown>:0 
  at BlazorApplicationInsights.ApplicationInsights.AddTelemetryInitializer (BlazorApplicationInsights.ITelemetryItem telemetryItem) <0x1fbedb0 + 0x000dc> in <filename unknown>:0 
  at BlazorApplicationInsights.Sample.Program+<>c.<Main>b__0_1 (BlazorApplicationInsights.IApplicationInsights applicationInsights) <0x1fbe658 + 0x00116> in <filename unknown>:0 
  at BlazorApplicationInsights.ApplicationInsights.InitBlazorApplicationInsightsAsync (Microsoft.JSInterop.IJSRuntime jSRuntime) <0x1fbba58 + 0x000ec> in <filename unknown>:0 
  at BlazorApplicationInsights.ApplicationInsightsComponent.OnAfterRenderAsync (System.Boolean firstRender) <0x1fbb458 + 0x000e4> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x20073c8 + 0x000ca> in <filename unknown>:0 
f.printErr @ blazor.webassembly.js:1

**Comment by IvanJosipovic** [comment]
I was able to reproduce this issue this morning and now its working again. My guess is something broke in the App Insights JS. Let me know if you see this issue again.

**Comment by GZidar** [comment]
I have experienced this error as well, and I think I have been able to reproduce it reliably (.net 6). If the WASM app loads and appInsights is working, and then the user enters an app URL in the browser (not following a link in the app navigating directly via URL) then this causes the blazor WASM app to reload and as soon as that happens the error above starts appearing on every subsequent navigation event.
